import "./globals.css";
import Nav from "@/Components/Nav";
import { Poppins } from "next/font/google";

const Pop = Poppins({
  subsets:["latin"],
  weight:["400","500","600"]
})


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Pop.className}`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
